整理以下從Credit Card Balance整理過來的欄位

1、COUNT_AMT_TOTAL_RECEIVABLE-->需要還款有幾個月份 sum

2-1、AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate -->ATM借錢佔額度的比例平均 median

2-2、AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate -->ATM借錢佔額度的比例最大 max

2-3、AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate -->ATM借錢佔額度的比例最小 min

2-4、AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate -->OTHER借錢佔額度的比例平均 median

2-5、AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate -->OTHER借錢佔額度的比例最大 max

2-6、AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate -->OTHER借錢佔額度的比例最小 min

2-7、AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate -->POS借錢佔額度的比例平均 median

2-8、AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate -->POS借錢佔額度的比例比例最大 max

2-9、AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate -->POS借錢佔額度的比例比例最小 min

3-1、AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate -->ATM借錢佔總借款額的比例 median

3-2、AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate -->OTHER借錢佔總借款額的比例 median

3-3、AMT_DRAWINGS_POS_ALL_DRAWINGS_rate -->POS借錢佔總借款額的比例 median

4-1、 CREDIT_LIMIT_MAX -->可用最大額度金額 max

4-2、CREDIT_LIMIT_MIN -->可用最小額度金額 min

4-3、CREDIT_LIMIT_MEDIAN -->可用中位數額度金額 median

4-4、CREDIT_LIMIT_MOST_RECENT -->最近可用額度金額 median

4-5、CREDIT_LIMIT_FAREST -->最久之前可用額度金額 median

5-1、RECEIVABLE PRINCIPAL_rate -->最大RECEIVABLE PRINCIPAL動用額度佔比 max

5-2、AMT_TOTAL_RECEIVABLE_rate -->最大AMT_TOTAL_RECEIVABLE動用額度佔比 max

7、有借錢時，平均一期還應還金額的多少%(AMT_PAYMENT_TOTAL_CURRENT/AMT_INST_MIN_REGULARITY)、(AMT_PAYMENT_CURRENT/AMT_INST_MIN_REGULARITY) median

7-1、 (AMT_PAYMENT_TOTAL_CURRENT/AMT_INST_MIN_REGULARITY)(要剔除AMT_INST_MIN_REGULARITY是0的)AMT_PAYMENT_TOTAL_CURRENT_MIN_REGULARITY_mean_rate -->有借錢時，AMT_PAYMENT_TOTAL_CURRENT平均一期還應還MIN_REGULARITY金額的多少% median

7-2、 (AMT_PAYMENT_CURRENT/AMT_INST_MIN_REGULARITY)(要剔除AMT_INST_MIN_REGULARITY是0的)
AMT_PAYMENT_CURRENT_MIN_REGULARITY_mean_rate -->有借錢時，AMT_PAYMENT_CURRENT平均一期還應還MIN_REGULARITY金額的多少% median

8、紀錄時間最久以前是多久MONTHS_BALANCE_start --> MONTHS_BALANCE紀錄開始時間 min

9、紀錄時間最近是幾個月以前 MONTHS_BALANCE_near --> MONTHS_BALANCE紀錄最近時間 max

10、有借錢紀錄時間最久是多久以前 AMT_BALANCE_MONTHS_start --> AMT_BALANCE紀錄開始時間 min

11、有借錢紀錄時間最近是多久以前 AMT_BALANCE_MONTHS_near --> AMT_BALANCE紀錄最近時間 max

13、AMT_TOTAL_RECEIVABLE_MAX -->最大總借款金額 max

14、AMT_DRAWINGS_CURRENT_MAX -->最大借款金額 max

X 15、最大借款金額占額度%(AMT_DRAWINGS_CURRENT/CREDIT_LIMIT MAX) AMT_DRAWINGS_CURRENT_MAX_rate -->最大借款金額占額度% max

16、最小借款金額(AMT_DRAWINGS_CURRENT MIN) AMT_DRAWINGS_CURRENT_MIN-->最小借款金額(，有踢除0) min

17、最小借款金額占額度%(AMT_DRAWINGS_CURRENT/CREDIT_LIMIT MIN) min

17-1、AMT_DRAWINGS_CURRENT_MIN_rate_MAX  -->最小借款金額占額度%(CREDIT_LIMIT_MAX) max

17-2、AMT_DRAWINGS_CURRENT_MIN_rate_MIN -->最小借款金額占額度%(CREDIT_LIMIT_MIN) min

17-3、AMT_DRAWINGS_CURRENT_MIN_rate_MEDIAN -->最小借款金額占額度%(CREDIT_LIMIT_MEDIAN) median

18、每筆貸款借錢時平均每次提領多少(AMT_DRAWINGS_CURRENT/CNT_DRAWINGS_CURRENT MEAN) AMT_DRAWINGS_CURRENT_CNT_rate median

19、每筆貸款借錢時平均每次提領多少占額度的% ((AMT_DRAWINGS_CURRENT/CNT_DRAWINGS_CURRENT MEAN)/CREDIT_LIMIT) AMT_DRAWINGS_CURRENT_CNT_CREDIT_LIMIT_rate median

a1:新增7個欄位：將同一個'SK_ID_PREV'彙整，列出NAME_CONTRACT_STATUS(先前信用期間合約狀態)發生的比例。併到credit_card_balance。 median

a2:新增2個欄位：將同一個'SK_ID_PREV'彙整，列出SK_DPD(先前信用期間逾期天數)發生的各項統計('max'(最多天),'mean'(平均天數))。max median

a3:新增1個欄位：將同一個'SK_ID_PREV'彙整，列出SK_DPD(先前信用期間逾期天數)發生的次數。median

a4:新增2個欄位：將同一個'SK_ID_PREV'彙整，列出SK_DPD_DEF(先前信用期間逾期天數(可容忍,忽略低金額))發生的各項統計('max'(最多天),'mean'(平均天數))。max median

a5:新增1個欄位：將同一個'SK_ID_PREV'彙整，列出SK_DPD_DEF(先前信用期間逾期天數(可容忍,忽略低金額))發生的次數。median

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

In [2]:
ccFE = pd.read_csv("..\\..\\datasets\\homecdt_fteng\\credit_card_balance_FE.csv")

In [3]:
ccFE.columns

Index(['SK_ID_CURR', 'SK_ID_PREV', 'COUNT_AMT_TOTAL_RECEIVABLE',
       'AMT_DRAWINGS_ATM_SUM', 'AMT_DRAWINGS_ATM_MAX', 'AMT_DRAWINGS_ATM_MIN',
       'AMT_DRAWINGS_OTHER_SUM', 'AMT_DRAWINGS_OTHER_MAX',
       'AMT_DRAWINGS_OTHER_MIN', 'AMT_DRAWINGS_POS_SUM',
       'AMT_DRAWINGS_POS_MAX', 'AMT_DRAWINGS_POS_MIN', 'CREDIT_LIMIT_MAX',
       'CREDIT_LIMIT_MIN', 'CREDIT_LIMIT_MEDIAN', 'CREDIT_LIMIT_MOST_RECENT',
       'CREDIT_LIMIT_FAREST', 'MONTHS_BALANCE_start', 'MONTHS_BALANCE_near',
       'AMT_TOTAL_RECEIVABLE_MAX', 'AMT_DRAWINGS_CURRENT_MAX',
       'AMT_DRAWINGS_CURRENT_MIN', 'AMT_RECEIVABLE_PRINCIPAL_MAX',
       'AMT_DRAWINGS_CURRENT_SUM', 'CNT_DRAWINGS_CURRENT_SUM',
       'AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate',
       'AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate',
       'AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate',
       'AMT_DRAWINGS_POS_ALL_DRAWINGS_rate', 'RECEIVABLE PRINCIPAL_rate',
       'AMT_TOTAL_RECEIVABLE_rate', 'CREDIT_LIMIT_MAX_rate',
       'AMT_DRAWINGS_CURRENT_MIN_rate_MAX',
       'AMT_DRAWINGS_CURRENT_MIN_rate_MIN',
       'AMT_DRAWINGS_CURRENT_MIN_rate_MEDIAN', 'AMT_DRAWINGS_CURRENT_CNT_rate',
       'AMT_DRAWINGS_CURRENT_CNT_CREDIT_LIMIT_rate',
       'AMT_BALANCE_MONTHS_start', 'AMT_BALANCE_MONTHS_near', 'Total_Months',
       'CREDIT_ACTIVE_Active_rate', 'CREDIT_ACTIVE_Approved_rate',
       'CREDIT_ACTIVE_Completed_rate', 'CREDIT_ACTIVE_Demand_rate',
       'CREDIT_ACTIVE_Refused_rate', 'CREDIT_ACTIVE_Sent proposal_rate',
       'CREDIT_ACTIVE_Signed_rate', 'ccb_SK_DPD_MAX', 'ccb_SK_DPD_MEAN',
       'ccb_SK_DPD_delay_count', 'ccb_SK_DPD_DEF_MAX', 'ccb_SK_DPD_DEF_MEAN',
       'ccb_SK_DPD_DEF_delay_count', 'AMT_INST_MIN_REGULARITY_count',
       'AMT_PAYMENT_TOTAL_MIN_REGULARITY_rate',
       'AMT_PAYMENT_MIN_REGULARITY_rate',
       'AMT_PAYMENT_TOTAL_CURRENT_MIN_REGULARITY_mean_rate',
       'AMT_PAYMENT_CURRENT_MIN_REGULARITY_mean_rate'],
      dtype='object')

### ccFE2整理出使用max的欄位

In [4]:
new_feature = []
new_feature = ['AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_ATM_MAX',
               'AMT_DRAWINGS_OTHER_MAX',
               'AMT_DRAWINGS_POS_MAX',
               'CREDIT_LIMIT_MAX',
               'AMT_TOTAL_RECEIVABLE_MAX',
               'AMT_DRAWINGS_CURRENT_MAX',
               'AMT_DRAWINGS_CURRENT_MIN_rate_MAX',
               'AMT_RECEIVABLE_PRINCIPAL_MAX',
               'AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate',
               'CREDIT_LIMIT_MAX_rate',
               'ccb_SK_DPD_MAX',
               'ccb_SK_DPD_DEF_MAX']
new_feature

['AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_ATM_MAX',
 'AMT_DRAWINGS_OTHER_MAX',
 'AMT_DRAWINGS_POS_MAX',
 'CREDIT_LIMIT_MAX',
 'AMT_TOTAL_RECEIVABLE_MAX',
 'AMT_DRAWINGS_CURRENT_MAX',
 'AMT_DRAWINGS_CURRENT_MIN_rate_MAX',
 'AMT_RECEIVABLE_PRINCIPAL_MAX',
 'AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate',
 'CREDIT_LIMIT_MAX_rate',
 'ccb_SK_DPD_MAX',
 'ccb_SK_DPD_DEF_MAX']

In [5]:
dict_type = {}
for i in new_feature:
    dict_type[i] = ['max']
num_aggregations = dict_type
num_aggregations

{'AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate': ['max'],
 'AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate': ['max'],
 'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate': ['max'],
 'AMT_DRAWINGS_ATM_MAX': ['max'],
 'AMT_DRAWINGS_OTHER_MAX': ['max'],
 'AMT_DRAWINGS_POS_MAX': ['max'],
 'CREDIT_LIMIT_MAX': ['max'],
 'AMT_TOTAL_RECEIVABLE_MAX': ['max'],
 'AMT_DRAWINGS_CURRENT_MAX': ['max'],
 'AMT_DRAWINGS_CURRENT_MIN_rate_MAX': ['max'],
 'AMT_RECEIVABLE_PRINCIPAL_MAX': ['max'],
 'CREDIT_LIMIT_MAX_rate': ['max'],
 'ccb_SK_DPD_MAX': ['max'],
 'ccb_SK_DPD_DEF_MAX': ['max']}

In [6]:
ccFE2 = ccFE.groupby('SK_ID_CURR').agg({**num_aggregations})
ccFE2.columns

MultiIndex([(  'AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max'),
            ('AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max'),
            (  'AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max'),
            (                            'AMT_DRAWINGS_ATM_MAX', 'max'),
            (                          'AMT_DRAWINGS_OTHER_MAX', 'max'),
            (                            'AMT_DRAWINGS_POS_MAX', 'max'),
            (                                'CREDIT_LIMIT_MAX', 'max'),
            (                        'AMT_TOTAL_RECEIVABLE_MAX', 'max'),
            (                        'AMT_DRAWINGS_CURRENT_MAX', 'max'),
            (               'AMT_DRAWINGS_CURRENT_MIN_rate_MAX', 'max'),
            (                    'AMT_RECEIVABLE_PRINCIPAL_MAX', 'max'),
            (                           'CREDIT_LIMIT_MAX_rate', 'max'),
            (                                  'ccb_SK_DPD_MAX', 'max'),
            (                              'ccb_SK_DPD_DEF_MAX', 'max')],
           )

In [7]:
columns = []
for m in ccFE2.columns:
    columns.append(f'CC_{m}_max')
ccFE2.columns = columns

In [8]:
ccFE2.reset_index(level=('SK_ID_CURR'),inplace=True)
ccFE2.head()

,SK_ID_CURR,"CC_('AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_ATM_MAX', 'max')_max","CC_('AMT_DRAWINGS_OTHER_MAX', 'max')_max","CC_('AMT_DRAWINGS_POS_MAX', 'max')_max","CC_('CREDIT_LIMIT_MAX', 'max')_max","CC_('AMT_TOTAL_RECEIVABLE_MAX', 'max')_max","CC_('AMT_DRAWINGS_CURRENT_MAX', 'max')_max","CC_('AMT_DRAWINGS_CURRENT_MIN_rate_MAX', 'max')_max","CC_('AMT_RECEIVABLE_PRINCIPAL_MAX', 'max')_max","CC_('CREDIT_LIMIT_MAX_rate', 'max')_max","CC_('ccb_SK_DPD_MAX', 'max')_max","CC_('ccb_SK_DPD_DEF_MAX', 'max')_max"
0,100006,NaN,NaN,NaN,NaN,NaN,NaN,270000,0.00,0.0,NaN,0.0,0.0,0,0
1,100011,1.0,0.0,0.0,180000.0,0.0,0.0,180000,189000.00,180000.0,1.000000,180000.0,1.0,0,0
2,100013,1.0,0.0,0.0,157500.0,0.0,0.0,157500,161420.22,157500.0,0.142857,157500.0,1.0,1,1
3,100021,NaN,NaN,NaN,NaN,NaN,NaN,675000,0.00,0.0,NaN,0.0,0.0,0,0
4,100023,NaN,NaN,NaN,NaN,NaN,NaN,225000,0.00,0.0,NaN,0.0,0.0,0,0

### ccFE3整理出使用min的欄位

In [9]:
new_feature = []
new_feature = ['AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_ATM_MIN',
               'AMT_DRAWINGS_OTHER_MIN',
               'AMT_DRAWINGS_POS_MIN',
               'CREDIT_LIMIT_MIN',
               'AMT_DRAWINGS_CURRENT_MIN',
               'AMT_DRAWINGS_CURRENT_MIN_rate_MIN',
               'AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate']
new_feature

['AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_ATM_MIN',
 'AMT_DRAWINGS_OTHER_MIN',
 'AMT_DRAWINGS_POS_MIN',
 'CREDIT_LIMIT_MIN',
 'AMT_DRAWINGS_CURRENT_MIN',
 'AMT_DRAWINGS_CURRENT_MIN_rate_MIN',
 'AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate']

In [10]:
dict_type = {}
for i in new_feature:
    dict_type[i] = ['min']
num_aggregations = dict_type
num_aggregations

{'AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate': ['min'],
 'AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate': ['min'],
 'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate': ['min'],
 'AMT_DRAWINGS_ATM_MIN': ['min'],
 'AMT_DRAWINGS_OTHER_MIN': ['min'],
 'AMT_DRAWINGS_POS_MIN': ['min'],
 'CREDIT_LIMIT_MIN': ['min'],
 'AMT_DRAWINGS_CURRENT_MIN': ['min'],
 'AMT_DRAWINGS_CURRENT_MIN_rate_MIN': ['min']}

In [11]:
ccFE3 = ccFE.groupby('SK_ID_CURR').agg({**num_aggregations})
ccFE3.columns

MultiIndex([(  'AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate', 'min'),
            ('AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate', 'min'),
            (  'AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate', 'min'),
            (                            'AMT_DRAWINGS_ATM_MIN', 'min'),
            (                          'AMT_DRAWINGS_OTHER_MIN', 'min'),
            (                            'AMT_DRAWINGS_POS_MIN', 'min'),
            (                                'CREDIT_LIMIT_MIN', 'min'),
            (                        'AMT_DRAWINGS_CURRENT_MIN', 'min'),
            (               'AMT_DRAWINGS_CURRENT_MIN_rate_MIN', 'min')],
           )

In [12]:
columns = []
for m in ccFE3.columns:
    columns.append(f'CC_{m}_min')
ccFE3.columns = columns

In [13]:
ccFE3.reset_index(level=('SK_ID_CURR'),inplace=True)
ccFE3.head()

,SK_ID_CURR,"CC_('AMT_DRAWINGS_ATM_MIN_CREDIT_LIMIT_MEDIAN _rate', 'min')_min","CC_('AMT_DRAWINGS_OTHER_MIN_CREDIT_LIMIT_MEDIAN _rate', 'min')_min","CC_('AMT_DRAWINGS_POS_MIN_CREDIT_LIMIT_MEDIAN _rate', 'min')_min","CC_('AMT_DRAWINGS_ATM_MIN', 'min')_min","CC_('AMT_DRAWINGS_OTHER_MIN', 'min')_min","CC_('AMT_DRAWINGS_POS_MIN', 'min')_min","CC_('CREDIT_LIMIT_MIN', 'min')_min","CC_('AMT_DRAWINGS_CURRENT_MIN', 'min')_min","CC_('AMT_DRAWINGS_CURRENT_MIN_rate_MIN', 'min')_min"
0,100006,NaN,NaN,NaN,NaN,NaN,NaN,270000,NaN,NaN
1,100011,1.000000,NaN,NaN,180000.0,NaN,NaN,90000,180000.0,2.0
2,100013,0.142857,NaN,NaN,22500.0,NaN,NaN,45000,22500.0,0.5
3,100021,NaN,NaN,NaN,NaN,NaN,NaN,675000,NaN,NaN
4,100023,NaN,NaN,NaN,NaN,NaN,NaN,45000,NaN,NaN

### ccFE4整理出使用median的欄位

In [14]:
new_feature = []
new_feature = ['AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate',
               'AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate',
               'AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate',
               'AMT_DRAWINGS_POS_ALL_DRAWINGS_rate',
               'CREDIT_LIMIT_MEDIAN',
               'CREDIT_LIMIT_MOST_RECENT',
               'CREDIT_LIMIT_FAREST',
               'AMT_PAYMENT_TOTAL_CURRENT_MIN_REGULARITY_mean_rate',
               'AMT_PAYMENT_CURRENT_MIN_REGULARITY_mean_rate',
               'AMT_DRAWINGS_CURRENT_CNT_CREDIT_LIMIT_rate',
               'AMT_DRAWINGS_CURRENT_CNT_rate',
               'CREDIT_ACTIVE_Active_rate',
               'CREDIT_ACTIVE_Approved_rate',
               'CREDIT_ACTIVE_Completed_rate',
               'CREDIT_ACTIVE_Demand_rate',
               'CREDIT_ACTIVE_Refused_rate',
               'CREDIT_ACTIVE_Sent proposal_rate',
               'CREDIT_ACTIVE_Signed_rate',
               'ccb_SK_DPD_MEAN',
               'ccb_SK_DPD_DEF_MEAN',
               'ccb_SK_DPD_delay_count',
               'ccb_SK_DPD_DEF_delay_count']
new_feature

['AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate',
 'AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate',
 'AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate',
 'AMT_DRAWINGS_POS_ALL_DRAWINGS_rate',
 'CREDIT_LIMIT_MEDIAN',
 'CREDIT_LIMIT_MOST_RECENT',
 'CREDIT_LIMIT_FAREST',
 'AMT_PAYMENT_TOTAL_CURRENT_MIN_REGULARITY_mean_rate',
 'AMT_PAYMENT_CURRENT_MIN_REGULARITY_mean_rate',
 'AMT_DRAWINGS_CURRENT_CNT_CREDIT_LIMIT_rate',
 'AMT_DRAWINGS_CURRENT_CNT_rate',
 'CREDIT_ACTIVE_Active_rate',
 'CREDIT_ACTIVE_Approved_rate',
 'CREDIT_ACTIVE_Completed_rate',
 'CREDIT_ACTIVE_Demand_rate',
 'CREDIT_ACTIVE_Refused_rate',
 'CREDIT_ACTIVE_Sent proposal_rate',
 'CREDIT_ACTIVE_Signed_rate',
 'ccb_SK_DPD_MEAN',
 'ccb_SK_DPD_DEF_MEAN',
 'ccb_SK_DPD_delay_count',
 'ccb_SK_DPD_DEF_delay_count']

In [15]:
dict_type = {}
for i in new_feature:
    dict_type[i] = ['median']
num_aggregations = dict_type
num_aggregations

{'AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate': ['median'],
 'AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate': ['median'],
 'AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate': ['median'],
 'AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate': ['median'],
 'AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate': ['median'],
 'AMT_DRAWINGS_POS_ALL_DRAWINGS_rate': ['median'],
 'CREDIT_LIMIT_MEDIAN': ['median'],
 'CREDIT_LIMIT_MOST_RECENT': ['median'],
 'CREDIT_LIMIT_FAREST': ['median'],
 'AMT_PAYMENT_TOTAL_CURRENT_MIN_REGULARITY_mean_rate': ['median'],
 'AMT_PAYMENT_CURRENT_MIN_REGULARITY_mean_rate': ['median'],
 'AMT_DRAWINGS_CURRENT_CNT_CREDIT_LIMIT_rate': ['median'],
 'AMT_DRAWINGS_CURRENT_CNT_rate': ['median'],
 'CREDIT_ACTIVE_Active_rate': ['median'],
 'CREDIT_ACTIVE_Approved_rate': ['median'],
 'CREDIT_ACTIVE_Completed_rate': ['median'],
 'CREDIT_ACTIVE_Demand_rate': ['median'],
 'CREDIT_ACTIVE_Refused_rate': ['median'],
 'CREDIT_ACTIVE_Sent proposal_rate': ['median'],
 'CREDIT_ACTIVE_Signed_rate': ['median'],
 'ccb_SK_DPD_MEAN': ['median'],
 'ccb_SK_DPD_DEF_MEAN': ['median'],
 'ccb_SK_DPD_delay_count': ['median'],
 'ccb_SK_DPD_DEF_delay_count': ['median']}

In [16]:
ccFE4 = ccFE.groupby('SK_ID_CURR').agg({**num_aggregations})
ccFE4.columns

MultiIndex([(    'AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate', 'median'),
            (  'AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate', 'median'),
            (    'AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate', 'median'),
            (                'AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate', 'median'),
            (              'AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate', 'median'),
            (                'AMT_DRAWINGS_POS_ALL_DRAWINGS_rate', 'median'),
            (                               'CREDIT_LIMIT_MEDIAN', 'median'),
            (                          'CREDIT_LIMIT_MOST_RECENT', 'median'),
            (                               'CREDIT_LIMIT_FAREST', 'median'),
            ('AMT_PAYMENT_TOTAL_CURRENT_MIN_REGULARITY_mean_rate', 'median'),
            (      'AMT_PAYMENT_CURRENT_MIN_REGULARITY_mean_rate', 'median'),
            (        'AMT_DRAWINGS_CURRENT_CNT_CREDIT_LIMIT_rate', 'median'),
            (                     'AMT_DRAWINGS_CURRENT_CNT_rate', 'median'),
            (                         'CREDIT_ACTIVE_Active_rate', 'median'),
            (                       'CREDIT_ACTIVE_Approved_rate', 'median'),
            (                      'CREDIT_ACTIVE_Completed_rate', 'median'),
            (                         'CREDIT_ACTIVE_Demand_rate', 'median'),
            (                        'CREDIT_ACTIVE_Refused_rate', 'median'),
            (                  'CREDIT_ACTIVE_Sent proposal_rate', 'median'),
            (                         'CREDIT_ACTIVE_Signed_rate', 'median'),
            (                                   'ccb_SK_DPD_MEAN', 'median'),
            (                               'ccb_SK_DPD_DEF_MEAN', 'median'),
            (                            'ccb_SK_DPD_delay_count', 'median'),
            (                        'ccb_SK_DPD_DEF_delay_count', 'median')],
           )

In [17]:
columns = []
for m in ccFE4.columns:
    columns.append(f'CC_{m}_median')
ccFE4.columns = columns

In [18]:
ccFE4.reset_index(level=('SK_ID_CURR'),inplace=True)
ccFE4.head()

,SK_ID_CURR,"CC_('AMT_DRAWINGS_ATM_SUM_CREDIT_LIMIT_MEDIAN _rate', 'median')_median","CC_('AMT_DRAWINGS_OTHER_SUM_CREDIT_LIMIT_MEDIAN _rate', 'median')_median","CC_('AMT_DRAWINGS_POS_SUM_CREDIT_LIMIT_MEDIAN _rate', 'median')_median","CC_('AMT_DRAWINGS_ATM_ALL_DRAWINGS_rate', 'median')_median","CC_('AMT_DRAWINGS_OTHER_ALL_DRAWINGS_rate', 'median')_median","CC_('AMT_DRAWINGS_POS_ALL_DRAWINGS_rate', 'median')_median","CC_('CREDIT_LIMIT_MEDIAN', 'median')_median","CC_('CREDIT_LIMIT_MOST_RECENT', 'median')_median","CC_('CREDIT_LIMIT_FAREST', 'median')_median",...,"CC_('CREDIT_ACTIVE_Approved_rate', 'median')_median","CC_('CREDIT_ACTIVE_Completed_rate', 'median')_median","CC_('CREDIT_ACTIVE_Demand_rate', 'median')_median","CC_('CREDIT_ACTIVE_Refused_rate', 'median')_median","CC_('CREDIT_ACTIVE_Sent proposal_rate', 'median')_median","CC_('CREDIT_ACTIVE_Signed_rate', 'median')_median","CC_('ccb_SK_DPD_MEAN', 'median')_median","CC_('ccb_SK_DPD_DEF_MEAN', 'median')_median","CC_('ccb_SK_DPD_delay_count', 'median')_median","CC_('ccb_SK_DPD_DEF_delay_count', 'median')_median"
0,100006,0.000000,0.0,0.0,NaN,NaN,NaN,270000,270000,270000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
1,100011,1.000000,0.0,0.0,NaN,NaN,NaN,180000,90000,180000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
2,100013,3.628571,0.0,0.0,NaN,NaN,NaN,157500,45000,157500,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.010417,0.010417,1.0,1.0
3,100021,0.000000,0.0,0.0,NaN,NaN,NaN,675000,675000,675000,...,0.0,0.588235,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
4,100023,0.000000,0.0,0.0,NaN,NaN,NaN,135000,225000,45000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0

### ccFE5整理出使用sum的欄位

In [19]:
ccFE5 = ccFE.groupby('SK_ID_CURR').agg({'COUNT_AMT_TOTAL_RECEIVABLE':'sum'})
ccFE5.reset_index(level=('SK_ID_CURR'),inplace=True)
ccFE5.head()

   SK_ID_CURR  COUNT_AMT_TOTAL_RECEIVABLE
0      100006                         0.0
1      100011                        32.0
2      100013                        16.0
3      100021                         0.0
4      100023                         0.0

### 合併ccFE2~5

In [20]:
ccFE2.shape

(103558, 15)

In [21]:
ccFE2 = pd.merge(ccFE2,ccFE3,how='left')

In [22]:
ccFE2.shape

(103558, 24)

In [23]:
ccFE2 = pd.merge(ccFE2,ccFE4,how='left')

In [24]:
ccFE2.shape

(103558, 48)

In [25]:
ccFE2 = pd.merge(ccFE2,ccFE5,how='left')

In [27]:
ccFE2.shape

(103558, 49)

In [29]:
ccFE2.head()

,SK_ID_CURR,"CC_('AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_ATM_MAX', 'max')_max","CC_('AMT_DRAWINGS_OTHER_MAX', 'max')_max","CC_('AMT_DRAWINGS_POS_MAX', 'max')_max","CC_('CREDIT_LIMIT_MAX', 'max')_max","CC_('AMT_TOTAL_RECEIVABLE_MAX', 'max')_max","CC_('AMT_DRAWINGS_CURRENT_MAX', 'max')_max",...,"CC_('CREDIT_ACTIVE_Completed_rate', 'median')_median","CC_('CREDIT_ACTIVE_Demand_rate', 'median')_median","CC_('CREDIT_ACTIVE_Refused_rate', 'median')_median","CC_('CREDIT_ACTIVE_Sent proposal_rate', 'median')_median","CC_('CREDIT_ACTIVE_Signed_rate', 'median')_median","CC_('ccb_SK_DPD_MEAN', 'median')_median","CC_('ccb_SK_DPD_DEF_MEAN', 'median')_median","CC_('ccb_SK_DPD_delay_count', 'median')_median","CC_('ccb_SK_DPD_DEF_delay_count', 'median')_median",COUNT_AMT_TOTAL_RECEIVABLE
0,100006,NaN,NaN,NaN,NaN,NaN,NaN,270000,0.00,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,100011,1.0,0.0,0.0,180000.0,0.0,0.0,180000,189000.00,180000.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,32.0
2,100013,1.0,0.0,0.0,157500.0,0.0,0.0,157500,161420.22,157500.0,...,0.000000,0.0,0.0,0.0,0.0,0.010417,0.010417,1.0,1.0,16.0
3,100021,NaN,NaN,NaN,NaN,NaN,NaN,675000,0.00,0.0,...,0.588235,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
4,100023,NaN,NaN,NaN,NaN,NaN,NaN,225000,0.00,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [30]:
ccFE2.rename(columns={'COUNT_AMT_TOTAL_RECEIVABLE':'COUNT_AMT_TOTAL_RECEIVABLE_sum'},inplace=True)

In [31]:
ccFE2.head()

,SK_ID_CURR,"CC_('AMT_DRAWINGS_ATM_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_OTHER_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_POS_MAX_CREDIT_LIMIT_MEDIAN _rate', 'max')_max","CC_('AMT_DRAWINGS_ATM_MAX', 'max')_max","CC_('AMT_DRAWINGS_OTHER_MAX', 'max')_max","CC_('AMT_DRAWINGS_POS_MAX', 'max')_max","CC_('CREDIT_LIMIT_MAX', 'max')_max","CC_('AMT_TOTAL_RECEIVABLE_MAX', 'max')_max","CC_('AMT_DRAWINGS_CURRENT_MAX', 'max')_max",...,"CC_('CREDIT_ACTIVE_Completed_rate', 'median')_median","CC_('CREDIT_ACTIVE_Demand_rate', 'median')_median","CC_('CREDIT_ACTIVE_Refused_rate', 'median')_median","CC_('CREDIT_ACTIVE_Sent proposal_rate', 'median')_median","CC_('CREDIT_ACTIVE_Signed_rate', 'median')_median","CC_('ccb_SK_DPD_MEAN', 'median')_median","CC_('ccb_SK_DPD_DEF_MEAN', 'median')_median","CC_('ccb_SK_DPD_delay_count', 'median')_median","CC_('ccb_SK_DPD_DEF_delay_count', 'median')_median",COUNT_AMT_TOTAL_RECEIVABLE_sum
0,100006,NaN,NaN,NaN,NaN,NaN,NaN,270000,0.00,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,100011,1.0,0.0,0.0,180000.0,0.0,0.0,180000,189000.00,180000.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,32.0
2,100013,1.0,0.0,0.0,157500.0,0.0,0.0,157500,161420.22,157500.0,...,0.000000,0.0,0.0,0.0,0.0,0.010417,0.010417,1.0,1.0,16.0
3,100021,NaN,NaN,NaN,NaN,NaN,NaN,675000,0.00,0.0,...,0.588235,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
4,100023,NaN,NaN,NaN,NaN,NaN,NaN,225000,0.00,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [32]:
ccFE2.to_csv('..\\..\\datasets\\homecdt_fteng\\previous_application_FE_w_CreditCard.csv',index = False)